### ISSUE TITLE
Add "compilation" type of release next to EP and LP

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#156]
Difference : 

EP and LP don't need to have the artist name displayed next to every song (it creates unnecessary redundancy) when compilations do, so these should have slightly different layouts.

**Comment by ismailghedamsi** [comment]
Should we also support singles?

**Comment by simonv3** [comment]
I don't think we should base the need for displaying artists on whether a track is an EP or LP or compilation, since that seems like it's fairly arbitrary? I feel like it has more to do with the type of people involved in the song (and so I feel like we would be better served by having better and stricter role descriptions (`TrackArtist.role` might need to be a preset list of things and I'm wonder if it makes sense to actually have a value called `coAuthor` on the `TrackArtist` table that would mean they get listed next to the artist, and if there's more than two they appear in the artist column).
