### ISSUE TITLE
Possibility to unlink Stripe Account

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#164]
Once a stripe account is verified there's no way to change it at the moment.

**Comment by simonv3** [comment]
So this will need a little bit of thinking through I think. 

We can't delete live accounts because they might contain user's money 

![Image](https://github.com/funmusicplace/mirlo/assets/485583/44ba353e-1d6d-41c2-8bbd-7d5e0ffd98d4)

[delete account](https://stripe.com/docs/api/accounts/delete)

If there's money in the connected account, we won't be able to delete it. 

@LouisLouiseKay I wonder if part of the problem here is to allow a user to change the details of their Stripe account rather than remove it? Which would be a different problem.

**Comment by LouisLouiseKay** [comment]
My thinking was for example in the event of a music band, where they might want to change who is receiving the money at some point for example if a member of the group leaves or if they decide some new member must handle the money. 

I guess then the question is, is the stripe account nominal (for that one person) or is it a stripe account for the whole band where they can change the person that it's tied to? I don't have a lot of experience with Stripe so I really don't know if you can change the owner of a stripe account.

**Comment by simonv3** [comment]
Hmm, yeah, this also ties into the ownership model of an artist, and it being tied to a user account. It feels like part of that problem is being able to change the owning user of an account on the Mirlo side. For the sake of right now though, I'm going to try and add a link that lets you at least change the stripe details on an account.

**Comment by LouisLouiseKay** [comment]
To be fair even on Bandcamp that friction isn't entirely resolved. The only thing that's really manageable is "who gets the money / where is it sent" but other than that, if you create a user account and call that user the name of your band, you've created a "Band account" and you don't have to use the listener oriented features. (It would be especially true if users have capacity to set their profile page as private https://github.com/funmusicplace/mirlo/discussions/158 )

**Comment by simonv3** [comment]
Considering it's now possible to let users change their stripe details, I'm going to put this back on the back burner cause I think it requires some serious thought about what this looks like.

**Comment by LouisLouiseKay** [comment]
Sounds good enough for now

**Comment by simonv3** [comment]
I had to undo the `account_update` value being sent to stripe when creating an AccountLink tempoarily because it sounds like you can't do this with a non-custom account. Need to check in with Stripe support about this.

**Comment by simonv3** [comment]
Checked in with stripe support. The link still works. People can change their stripe information or log in with a different account. So I think this is good enough for now.
