### ISSUE TITLE
Adjustments to existing features, to streamline pre-order presentation

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#219]
Pre-order albums mean the full album is only downloadable at release date.

This is a list of small tweaks that could allow us to use what's already there to have a nice pre-order page creation process : 

- [x] Next to "publish", there could be a "publish as pre-order" button : 

Wording.

When publishing as pre-order :

- [x] update button would be "update pre-order"
- [x] release date would be "will be released on" or "release on" instead of past tense "released on".
- [x] "buy" button would be "pre-order".
- [x] Don't include download in confirmation email when pre-order.

**Comment by simonv3** [comment]
In the meantime, we could just as a temporary workaround add small text under the publish button. For example if the release date is "in the future", have a disclaimer that says "this album is due to be released in xxx days/weeks/months, you might want to choose a song for people to listen as a preview, and lock the others under must own until release."

This would help nudging people into realizing "you can do this" even if it's not the smoothest flow

@LouisLouiseKay

**Comment by simonv3** [comment]
> this button would just default all tracks to "enable free listen at release date".

It's not clear to me why this button would have this effect
