### ISSUE TITLE
Homepage to not be a log-in wall anymore

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#446]
Right now the homepage only displays posts by followed artists. The behavior is inconsistent wirh and the fact albums are just all the newly released albums, so you'd expect latest posts to be all the newly posted public posts.

Instead, there should be a "Feed" or "timeline" or "Posts" tab in the user collection / wishlist area, which displays specifically all the followed artists posts.

**Comment by simonv3** [comment]
I think the home page for a logged in user should start to match the home page of the logged out user. 

| |
|---|
| Same content now, replace mailing list button with signup | 
| new releases (only 5) |
| recent purchases / subscriptions (with an animation like how bandcamp does it, so that it looks like they're happening in the moment) |
| posts |

**Comment by LouisLouiseKay** [comment]
Yeah agreed there's no need to hide the sign-up process or the releases anymore.
