### ISSUE TITLE
Music on Mirlo doesn't continue playing if phone locks

### ISSUE THREAD

**Issue by simonv3** [funmusicplace/mirlo#516]
1. Play an album on Mirlo
2. Let your phone go to sleep / or lock whatever
3. Song finishes but doesn't switch to the next song

I don't know if this is a limitation of iOS Safari. There's already some hiccups around playing music on iOS Safari. It doesn't always start right away. I think this has to do with audio output needing to be triggered by a user on iOS Safari

**Comment by simonv3** [comment]
This looks like a limitation of iOS Safari https://discussions.apple.com/thread/253331448?sortBy=best

**Comment by graue** [comment]
For a personal project (release of an album I made), I worked around this by creating a constant-bitrate* mp3 of the entire album, and designed it so that clicking to play an individual track actually seeks to the start time of that track within the full-album mp3.

I listen to the 'timeupdate' event on the `<audio>` element to see when to update which track is playing on the page.

*The seeking is inaccurate if the mp3 is VBR, and Apple still doesn't support Opus.

**Comment by simonv3** [comment]
Hmm, interesting @graue . for bandwidth reasons we stream the music using segments and hls, so the entire file isn't available. I've seen at Resonate for example that expecting a 1hr song to load doesn't always do so successfully in the browser. Have you experienced that?

**Comment by graue** [comment]
No, I haven't seen that, but this was for a 20 minute long album.

My thinking was that browsers will make Range requests to not download irrelevant sections of the audio, but my personal project doesn't have to scale, so I didn't investigate the behavior in detail. This [preload attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#preload) might be relevant?

**Comment by simonv3** [comment]
this sounds like it's been resolved simply by waiting. i'm now halfway through an album and it's still playing

i think it was fixed by this but not sure 

https://bugs.webkit.org/show_bug.cgi?id=261554
